name: Trigger invocation

on:
  push:
    branches: 
      - 'master' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --cli-binary-format raw-in-base64-out \
            --function-name aws-managed-services-versions-fetch \
            --invocation-type Event \
            --payload '{ "output_file": "index.html" }' \
            response.json